//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ha_Systems_Proyect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.HOSPEDAJE = new HashSet<HOSPEDAJE>();
        }

        public int Id_cliente { get; set; }
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string Nombre { get; set; }
        [Display(Name = "Apellido")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string Apellido { get; set; }
        [Display(Name = "Celular")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string Celular { get; set; }
        [Display(Name = "Cedula")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [StringLength(11, ErrorMessage = "No cumple con requisisto de cedula",
              MinimumLength = 11)]
        public string Cedula { get; set; }
        [Display(Name = "Correo electrónico")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*",
       ErrorMessage = "Dirección de Correo electrónico incorrecta.")]
        [StringLength(100, ErrorMessage = "Longitud máxima 100")]
        [DataType(DataType.EmailAddress)]
        public string Correo { get; set; }
        [Display(Name = "Direccion")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string Direccion { get; set; }
        [Display(Name = "Ciudad")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        public string Ciudad { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSPEDAJE> HOSPEDAJE { get; set; }
    }
}
