//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ha_Systems_Proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public int Id_inventario { get; set; }
        public Nullable<int> Asignacion { get; set; }
        public string Ubicacion { get; set; }
        public string Marca { get; set; }
        public Nullable<int> Numero_serie { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad { get; set; }
    }
}
