//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ha_Systems_Proyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITOR_SESSION
    {
        public int Id_monitoreo { get; set; }
        public Nullable<int> Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_inicio { get; set; }
        public Nullable<System.TimeSpan> Hora_inicio { get; set; }
        public Nullable<System.TimeSpan> Hora_fin { get; set; }
        public Nullable<System.DateTime> Fecha_fin { get; set; }
    
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
